### ISSUE TITLE
[ENG-109] Epic:`theme` customizations for React components

### ISSUE THREAD

**Issue by tomkit** [supaglue-labs/supaglue#17]
<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-109](https://linear.app/supaglue/issue/ENG-109/epictheme-and-variables-customizations-for-react-components)</sub>

**Comment by asdfryan** [comment]
This is now available in `main`, to be included in the `0.2.0` release.

We have provided 2 themes (`defaultTheme` and `darkTheme`) that can be passed into the `SupaglueProvider`. 

```
// TUTORIAL: Uncomment this
import { darkTheme } from '@supaglue/nextjs';
// ...
 <SupaglueProvider
   customerId={customerId}
   // TUTORIAL: Uncomment this
   theme={darkTheme}
 >
```

![image](https://user-images.githubusercontent.com/1498449/217958765-3de827ed-c680-4dd9-8081-d6c965d467fb.png)

Furthermore, the `theme` class can be further overridden to change background colors, primary/danger color schemes, or even element-specific overrides.
