### ISSUE TITLE
[SUP1-15] Notification webhooks

### ISSUE THREAD

**Issue by tomkit** [supaglue-labs/supaglue#223]
<sub>From [SyncLinear.com](https://synclinear.com) | [SUP1-15](https://linear.app/supaglue/issue/SUP1-15/notification-webhooks)</sub>

**Comment by asdfryan** [comment]
This is done.

Configuration endpoints: https://www.postman.com/supaglue/workspace/supaglue-public/folder/18172762-4392a766-110e-4559-9cd5-a4ceeaa20e19?ctx=documentation
