### ISSUE TITLE
[SUP1-164] Make webhooks durable

### ISSUE THREAD

**Issue by lucasmarshall** [supaglue-labs/supaglue#347]
Right now they are best-effort

<sub>From [SyncLinear.com](https://synclinear.com) | [SUP1-164](https://linear.app/supaglue/issue/SUP1-164/make-webhooks-durable)</sub>

**Comment by lucasmarshall** [comment]
What I heard was performance and reliability issues dealing with high-volume CDC data events where dropping an event resulted in data loss.

Whereas our events don't contain data, but metadata. We are also batch and low-volume. We also have other parts of the system that are not reliable, e.g. the tickets that Albert has logged, so it seems like to address reliability holistically we have to actually take on more tickets/work in addition to this one

Planning for the week; can chat more in-office

**Comment by lucasmarshall** [comment]
Given the comments during the Warmly call that indicated their concerns about the reliability here, I think we should do something.

**Comment by lucasmarshall** [comment]
Given sync frequency I think this is OK for now

**Comment by tomkit** [comment]
Migrated to internal project management tool.
