### ISSUE TITLE
[SUP1-186] Improve Postgres memory usage characteristics for Supaglue's syncs

### ISSUE THREAD

**Issue by tomkit** [supaglue-labs/supaglue#359]
Currently it scales by # records synced instead of being constant.

<sub>From [SyncLinear.com](https://synclinear.com) | [SUP1-186](https://linear.app/supaglue/issue/SUP1-186/improve-postgres-memory-usage-characteristics-for-supaglues-syncs)</sub>

**Comment by albertyfwu** [comment]
one low hanging fruit is to do incremental syncs

**Comment by albertyfwu** [comment]
implemented incremental syncs. 

next we could try writing records directly to the main table on the first sync

**Comment by tomkit** [comment]
Migrated to internal project management tool.
