### ISSUE TITLE
[SUP1-101] Consider putting different customers' data in different DB schemas / sharding

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#368]
Right now we write all contacts, accounts, etc. into the same tables. This makes things very non-performant and not ideal.

<sub>From [SyncLinear.com](https://synclinear.com) | [SUP1-101](https://linear.app/supaglue/issue/SUP1-101/consider-putting-different-customers-data-in-different-db-schemas)</sub>

**Comment by tomkit** [comment]
Migrated to internal project management tool.
