### ISSUE TITLE
[SUP1-197] Enable fast creation of embedded link in MGMT portal

### ISSUE THREAD

**Issue by tomkit** [supaglue-labs/supaglue#382]
* Quick way to compose Embedded Link
* Quick way to create customer and make a first api call

<sub>From [SyncLinear.com](https://synclinear.com) | [SUP1-197](https://linear.app/supaglue/issue/SUP1-197/streamline-getting-started)</sub>

**Comment by asdfryan** [comment]
I've already done this @albertyfwu

**Comment by albertyfwu** [comment]
did you do the embedded link part too?

**Comment by tomkit** [comment]
Migrated to internal project management tool.
