### ISSUE TITLE
[SUP1-139] missing scope for fetching hubspot users doesn't stop activity

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#386]
instead, we just see heartbeat timeout

<sub>From [SyncLinear.com](https://synclinear.com) | [SUP1-139](https://linear.app/supaglue/issue/SUP1-139/missing-scope-for-fetching-hubspot-users-doesnt-stop-activity)</sub>

**Comment by tomkit** [comment]
Migrated to internal project management tool.
