### ISSUE TITLE
[SUP1-201] Fix bug switching apps in management UI

### ISSUE THREAD

**Issue by george-xing** [supaglue-labs/supaglue#393]
<sub>From [SyncLinear.com](https://synclinear.com) | [SUP1-201](https://linear.app/supaglue/issue/SUP1-201/fix-bug-switching-apps-in-management-ui)</sub>

**Comment by tomkit** [comment]
test

**Comment by george-xing** [comment]
Still running into issues, the dropdown menu is sticky
https://www.loom.com/share/93926e13ba0748dab24dbbe6dbb61353

**Comment by asdfryan** [comment]
Where are you running into this? I can't reproduce it in prod or locally? Have you pulled from head recently?

**Comment by asdfryan** [comment]
The problem was that the link wasn't spanning the whole row in the menu. I fixed that in the above PR.
