### ISSUE TITLE
[SUP1-209] set `additionalProperties: false` everywhere

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#414]
Now that this is in: https://github.com/supaglue-labs/supaglue/pull/413, we should add `additionalProperties: false` to all schemas in our OpenAPI spec to reject requests with extra properties

<sub>[SUP1-209](https://linear.app/supaglue/issue/SUP1-209/set-additionalproperties-false-everywhere)</sub>

**Comment by tomkit** [comment]
Migrated to internal project management tool.
