### ISSUE TITLE
Write prisma generator to generate ts types for DB model for use with pg library

### ISSUE THREAD

**Issue by tomkit** [supaglue-labs/supaglue#431]
For pg COPY command, we use pg and pg-copy-streams libraries. For more type safety and to avoid errors, we should implement our own prisma generator (or stop using prisma for common model tables)

https://www.prisma.io/docs/concepts/components/prisma-schema/generators

**Comment by tomkit** [comment]
I don't think we need this if we move off of prisma for CRM objects

**Comment by albertyfwu** [comment]
if we continue to use prisma, we might want to consider this: https://safeql.dev/
