### ISSUE TITLE
Consider using webhook for learning about deleted records

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#495]
we currently poll the list endpoints to get archived records, but this is bad for a few reasons:

1. After 90 days, archived records get permanently deleted and aren't queryable --- this is ok since it's unlikely that we stop syncing for 90 days in a row.
2. Bigger reason: there is no /search endpoint for archived records, so we have to use the list endpoint, which doesn't allow filtering by timestamp > highwatermark. Therefore, if a customer deletes a huge number of records, even if we "incrementally" pull new data from hubspot, we're not doing so for archived data, and it can be very expensive.

we could consider using webhook.

**Comment by tomkit** [comment]
Migrated to internal project management tool.
