### ISSUE TITLE
Reconsider SELECT DISTINCT ON when merging data from temp table into object table

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#497]
// IMPORTANT: we need to use DISTINCT ON because we may have multiple records with the same remote_id
      // For example, hubspot will return the same record twice when querying for `archived: true` if
      // the record was archived, restored, and archived again.
      // TODO: This may have performance implications. We should look into this later.

https://github.com/supaglue-labs/supaglue/pull/494

**Comment by albertyfwu** [comment]
@george-xing this is not just for hubspot. this applies for any remote connection

**Comment by tomkit** [comment]
Migrated to internal project management tool.
