### ISSUE TITLE
Consider abstractions/refactoring of [CommonModel]Service and hubspot/salesforce clients to simplify future connector development

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#502]
There's a lot of duplicated code for connectors and reading/writing/fetching common models right now.

We might want to spend some time refactoring / making better abstractions here to make future development easier. For example:
1. for every object, across both HS and salesforce, we write the same code over and over to page over responses and pipe things from HS/SF into PassThrough, and it’s relatively complicated. This is likely code that needs to be used for most future connectors, so it would be nice to abstract this away to make new connector development simpler.
2. 90% of the code in AccountService, ContactService, *Service is the same. We could probably make that abstracted as well

**Comment by tomkit** [comment]
Migrated to internal project management tool.
