### ISSUE TITLE
Salesforce potentially missing data

### ISSUE THREAD

**Issue by ledniy** [supaglue-labs/supaglue#532]
Hi there, I'm also working on internal CRM sync and was curious about your implementation, so I think you might have a problem getting all updates from salesforce just by using `WHERE SystemModstamp > ${updatedAfter.toISOString()} ORDER BY SystemModstamp` as SystemModstamp isn't a unique field, and some updates might be applied in bulk, which will result in equal SystemModstamp. In our case, we use the following query to ensure getting all records even if they have the same timestamp:
`where ((LastModifiedDate = ${since} and Id > '${lastId}') or LastModifiedDate > ${since}) order by LastModifiedDate asc, Id asc`
We are using `jsforce`, and maybe that problem was only due to pagination, but we made it work correctly after adding a secondary field, and now we can go over all data even with `limit 1`.
I will be glad to hear your thoughts.

**Comment by tomkit** [comment]
@ledniy Thanks for taking a look filing an issue! Indeed, we should probably use something like `WHERE SystemModstamp >= ${updatedAfter.toISOString()} ORDER BY SystemModstamp` to catch scenarios where something changed with equal `SystemModstamp`. Since we leverage `MERGE` in Postgres on the destination side of this sync, it would gracefully handle duplicate updates as well. We'll us this ticket to track the improvement.

**Comment by albertyfwu** [comment]
Hey @ledniy, could you give an example/details of the issue you saw? If updates are applied in bulk (I assume in a transaction), then won't a read query either see all the updates, or none of the updates?

With regards to pagination and losing records that way, bulk 2.0 query seems to execute the query, store the results, and then we page through those generated results (which are static), so I don't think we should see an issue there.

Let me know if I've made some wrong assumption / misunderstood. Thanks!

**Comment by ledniy** [comment]
@albertyfwu I didn't really test it with your version, I just remembered the case that we faced on our own implementation. If it's not applicable with bulk 2.0 that's really nice, I'll consider implementing it the same way.
