### ISSUE TITLE
Implement Properties API

### ISSUE THREAD

**Issue by george-xing** [supaglue-labs/supaglue#547]
Problem:
* Developers can write to custom properties, but only if the custom properties exist. If the property doesn't exist, they must first check to see if it exists via CRM providers API. This custom logic needs to be implemented N times per CRM

Solution
* CRUD endpoints for properties
* Allow developers to pass optional and provider-specific parameters into the request

**Comment by tomkit** [comment]
Migrated to internal project management tool.
