### ISSUE TITLE
Refactor to use the same code paths for manually cleaning up temporal syncs and spinning them up originally

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#590]
In normal operation, we rely on the `processSyncChanges` workflow to spin up new temporal workflows/schedules for `runSync`. This code is in `sync-worker`. However, we also have a manual endpoint which we can hit when things go out of sync (only if people are manually deleting/truncating tables and/or deleting/creating schedules/workflows in Temporal). This manual endpoint does many of the same things as `processSyncChanges`, but the code is in `api`. We should share the code.

https://github.com/supaglue-labs/supaglue/pull/589

**Comment by tomkit** [comment]
Migrated to internal project management tool.
