### ISSUE TITLE
Create endpoint/code to kill in-progress Temporal sync workflows but not schedules

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#591]
Sometimes we might deploy new code for sync workflows that is backwards incompatible.

We should have some way of killing existing workflows and either
1. letting the schedule start a sync the next time, or
2. immediately trigger a workflow to replace the one that was ongoing

We probably want to do this in a way that records in synchistory instead of just force terminating.

**Comment by tomkit** [comment]
Migrated to internal project management tool.
