### ISSUE TITLE
Make existing syncs respect integration's new sync period configuration faster

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#626]
Right now, when a sync period is changed for an integration, we wait until the next `processSyncChanges` Temporal workflow call (currently triggers 1x per minute) to update all existing syncs to the new period. We should make a best-effort call to do it immediately.

This is a follow-up for https://github.com/supaglue-labs/supaglue/issues/552

**Comment by tomkit** [comment]
Migrated to internal project management tool.
