### ISSUE TITLE
Avoid missing hubspot records that don't show up in search endpoint immediately

### ISSUE THREAD

**Issue by albertyfwu** [supaglue-labs/supaglue#665]
https://blog.sequin.io/hubspot-to-postgres/

**IMPORTANT**: We also should fix hubspot's search `updatedAfter` filter to make sure that we don't miss deletes.

Right now, if an `owner` is updated, `updatedAt` will change. However, if it's archived, there is no `archivedAt` property, and so when we filter for `archivedAt > updatedAt`, we won't get the new change. We should add buffer time for this reason too.

**Comment by tomkit** [comment]
Migrated to internal project management tool.
